# Generated by Django 5.1.3 on 2024-12-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_created_at_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
    ]
