XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        X X
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XX XXXX XXXXX XX
        X

        XXXXXXX X X
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXX XXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXX XXXXX
        X

        XXXXXXXXXXXXXXX XXXX X
            XXXXXXXX XXX XXXXX XX XXXXXXX XXXX XXXXXX XX
            XXXXXXXXXX XXXXX  XX XXXXXX XX XXXXXX XXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
        XXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXX XXXXXXXX gettext(u'Créer une nouvelle publication') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Accueil') XXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBXX gettext(u'Déconnexion') XXXX
            BBBB
                XX XXXXXXBBB BBBBBBBXX gettext(u'Login') XXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX     
    XXXXXX

    XXXX XXXXXXX XX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX gettext(u'Titre')  X XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXX gettext(u'Contenu')  X XXXXXXXXXXXX
        XXXXXX
        BB BBBBBBBBBB
            XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX
        BBBBB
        XXXXX
            XXXXXXXX gettext(u'Auteur') XXXXXXXXXX 
        XXXXXX
        XXXXX
            XXXXXXXX gettext(u'Catégorie') XXXXXXXXXX 
        XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Publié le') X FFFFFFF F FF FFFF
        XXXXXX

        BBBB BBBBBBBBBBBBBB
        
        BB BBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXX gettext(u'Modifier') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Supprimer') XXXX
            XXXXXX
        BBBBB
    XXXXXX
XXXXXXX
XXXXXXX