XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        X X
            XXXXXXXXXXX XXXXXXXXXXX XX XXXXXX XXX XX XXXXXXX XX XX XXXXXXX XXXX XXXXXX XXXX XX XXXXXXX XXXXXX XX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XX X
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXX
            XXXXXXXX XXXX XX
        X

        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXX XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXX X
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX    
        XXXX gettext(u'Connexion') XXXXX

        
        XXXX XXXXXXXX XXX XXXXXXXX XXXXXXXX XX XXXXXXXXXX XXX
        BB BBBBBBBB
            XXXX XXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    XXXXXXX
                BBBBBB
            XXXXXX
        BBBBB

        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
              XXXX XXXXXXXX XX XXXXXXXXXX XXXX XXXXXX XXXXX XXX XXX XXXXXXXX XXXXX XXX
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Connexion') XXXXXXXXX
        XXXXXXX

        XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX gettext(u"Retour à l'accueil") XXXX
    XXXXXX

XXXXXXX
XXXXXXX
