# Generated by Django 5.1.3 on 2024-12-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_author_remove_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_all_posts', 'Peut modifier toutes les publications')]},
        ),
    ]
