XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
        XX XXXXX XXXXXXX XX XX XXXX XX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XX X
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXXXX XXXXX
        X

        XX XXXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X X
            XXXXXXX XXXX XX
        X

        XXXXXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
    XXX XXXXXXXXXXXXX XXXXXXXX gettext(u'Es-tu sûr de vouloir supprimer cette publication')  XXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX
        BBBBBBBBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX
    XXXXXXX        

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Titre')  XXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Contenu')  XXXXXXXXXX XXXX
        XXXXXX

        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Supprimer') XXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Annuler') XXXX
        XXXXXXX
    XXXXXX

XXXXXXX
XXXXXXX
