XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        X X
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XX X
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXX XXXXX
        X

        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XX XXXX XXXXX XX
        X

        XXXXXXX X X
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXX XXXXXX XXXX XXXXXXXXX XXXX XXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXX XXXXXXXX X
            XXXXXXX XXXXXX
            XXXXXXX XXXXXXXXX
        X

        XXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXX X
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        X X
            XXXXXXXXXXXXXXXX XXXXX
        X

        XX XXXXX XXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
    XXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Créer une nouvelle publication') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Accueil') XXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBXX gettext(u'Déconnexion') XXXX
            BBBB
                XX XXXXXXBBB BBBBBBBXXXXXXXXXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX 
    XXXXXX

    XXXX XXXXXXXXXX XX XXXXXXXX XX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXXX
                    XXXXXXXX XXXX XXXXXX XX XXXX XXXXX XXXXXX XXX XXXX XXX XXX XXXXXXXXXX
                XXXXXX
            BBBBB
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Créer la publication') XXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX