XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XX XXXXX XXXXXXX XX XX XXXX XX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
        X

        XX XXXXX XX XXXXXXXXXX XX
        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XX 
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXX XX X
            XXXXXXXXXX XXXXX
            XX XXXXXXX XX XX
            XX XXXXXXXXXXXX XXXXXXX XX
        X

        XXXXXXX X X
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXX XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXX
        X
        
        XX XXXXXXXXX XXXXXXXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XX XXXXX XXX XXXXXX XX XXXXXXXXXX XX
        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXX XXXXXX XXXX XXXXXXXXX XXXX XXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX XX XXXXX XX XXXXXXXXXX XXXX XXXXXX XXX XXXXXXXXXXXX XX
        X

        XX XXXXX XXXXXXXXXX XXXX XXX XXXXXXXX XX
        XXXX XXXXXXXX X
            XXXXXXX XXXXXX
            XXXXXXX XXXXXXXXX
        X

        XX XXXXXX XX XXXXXXXXXX XX
        XXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXX XXXXXX XXXX XXXXXXX XX
        XXXXXX X
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
        X

        XX XXXXX XX XXXXXX XX XXXXXX XX
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXXXX XX XXXXX XXXXXXXX XXX XXX XXXXX XX
        X X
            XXXXXXXXXXXXXXXX XXXXX XX XXXXXX XX XXXXXXXXXXXX XX
        X

        XX XXXXX XXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
    XXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX gettext(u'Modification de publication') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Accueil') XXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX       
            BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBXX gettext(u'Déconnexion') XXXX
            BBBB
                XX XXXXXXBBB BBBBBBBXX gettext(u'Connexion') XXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX     
    XXXXXX

    XXXX XXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXXX XXX
            

            XXXX XXXXXXX XX XXXXXXX XXXXXXXX XX XXXXXXXXXX XXX
            BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXXX
                    XXX gettext(u'Il y a des erreurs dans votre formulaire. Veuillez les corriger et réessayer') XXXXX
                XXXXXX
            BBBBB

            XXXX XXXXXX XXXX XXXXXXXXX XXX
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Sauvegarder les modifications') XXXXXXXXX
        XXXXXXX
    XXXXXX

XXXXXXX
XXXXXXX