XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XX XXXXX XXXXXXX XX XX XXXX XX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XX XXXXXX XXXXX XX
        X

        X X
            XXXXXXXXXXXXXXXX XXXXX
        X

        XX XXXXX XX XXXXXXXXXX XX
        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXX XXXX XXXXX XX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXX X X
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXX XX X
            XXXXXXXXXX XXXXX
        X

        XX XXXXX XX XX XXXX XX
        XX X
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X

        XX XXXXXXXXX XXX XXXXX XX
        XXXXX X
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XX XXXXX XXXXXX XXX XXXXXX XXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
        X

        XXXXX XX X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXX
        X

        XX XXXXX XXXX XXXXXX XXXX XX
        XXXXX XXX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XX XXXX XX XXXXXXXXXXX XX
        XXXXX XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XX XXXXX XXX XXXXXXXX XX
        XX X
            XXXXXXXX XX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXX XX
        X

        XX XXXXX XX XXXXXX XXXX XXXXX XX XXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXX XXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXX XXXXX
        X

        XXXXXXXXXXXXXXX XXXX X
            XXXXXXXX XXX XXXXX XX XXXXXXX XXXX XXXXXX XX
            XXXXXXXXXX XXXXX  XX XXXXXX XX XXXXXX XXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXXX XXX XXXXXXX XX
        XXXX X
            XXXXXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXX XXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXX XXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXX XXXXXX X
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXXXX XXX XXXXXXX X XXXXXX XX
        XXXX XXXXXX XXXX XXXXXX X
            XXXXXX XXXXX
        X

        XX XXXXXXXXXX XXXXX XXX XXXXXXXX XX XXXXXXXXXX XX
        XXXX XXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX XXXXX XXXX XX XXXXXXXXX XX XXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB
    XXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX gettext(u'Toutes les publications') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Créer une nouvelle publication') XXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBXX gettext(u'Déconnexion') XXXX  XXXX XXXX XX XXXXXXXXXXX XXX
            BBBB
                XX XXXXXXBBB BBBBBBBXX gettext(u'Connexion') XXXX  XXXX XXXX XX XXXXXXXXX XXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXX
    XXXXXX   

    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Bonjour') X XXXXX  XXXX XXXXXXXXX XX XXX XX XXXXXXXXXXXXX XXX

    XXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX gettext(u'Filtrer par catégorie')  XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXX  gettext(u'Toutes les catégories')  XXXXXXXXXXX
            BBB BBBBBBBB BB BBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    
        XXXXXX XXXXXXXXXXX gettext(u'Filtrer par utilisateur')  XXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXXX XXXXXXXXXXX  gettext(u'Tous les utilisateurs')  XXXXXXXXXXX
            BBB BBBB BB BBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Filtrer') XXXXXXXXX
    XXXXXXX

    XXXX XXXXXXXXX XX XX XXXXX XXX XXXXXXXXXXXX XXX
    XXXX
        BBB BBBB BB BBBBB
        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBXX
        XXXX XXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX
            BB BBBBBBBBBB
                XXXX XXXXXX XXXXXXX
            BBBBB
            XX XXXXXXXXXXXXX gettext(u'De')  X XXXX
            XX XXXXXXXXXXXXX gettext(u'Publié le')  FFFFFFF F FF F FFFFXXXX
        XXXXXX
        XXXX
        BBBBBB
    XXXXX
XXXXXXX
XXXXXXX